### PR TITLE
Some fixes and improvements (retake)

### PR DESCRIPTION
**Pull request by soywiz**
This is a small cleanup on the changes I did.

Included changes:

* Fixes the problem where the JVM target hanged
* Fixes a timestamp issue
* Bumps korge and gradle
* Supports rendering by using NativeImage (toggleable via environment variable + gradle task)
* PNG was not available and some image rendering didn't work
* JS WebSocket didn't work because the open event was triggered before registration
* Reduced memory usage assigned to the JVM to avoid OOM on CI
* Removed fail-fast on CI so if one platform fails, the other ones continue
* ThreadLocal additions to support K/N

Hopefully this time it will work: https://github.com/soywiz/korjector/actions

### CODE REVIEW

**Comment by soywiz** [comment]
final_boss

no

running

**Comment by soywiz** [comment]
5u04hf

**Comment by soywiz** [comment]
mail

**Review by SerVB — APPROVED** [review]
Thank you very much for the changes! Yep, it's a strange story with building so let's disable what's not working.

**Pull request merged**
