### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by soywiz**
This is a small cleanup on the changes I did.

Included changes:

* Fixes the problem where the JVM target hanged
* Fixes a timestamp issue
* Bumps korge and gradle
* Supports rendering by using NativeImage (toggleable via environment variable + gradle task)
* PNG was not available and some image rendering didn't work
* JS WebSocket didn't work because the open event was triggered before registration

Instead of several PRs I have created a single PR with several commits, so maybe makes sense to rebase instead of squash and merge.

### CODE REVIEW

**Comment by SerVB** [comment]
Hi @soywiz! Looks like I had to manually allow running CI here but now it's failed. Any ideas how it can be solved?

**Comment by soywiz** [comment]
Woops, that error looks related to K/N or LLVM. But looking, it seems that the version I released was using Kotlin 1.6.0-RC.
I have triggered a new release using Kotlin 1.6.0-RC2 here: https://github.com/korlibs/korge-next/releases/tag/v2.4.8
Let's see if that solves the issue. I'm going to add a commit using that version, then after it is released you can try to re-run CI

**Comment by soywiz** [comment]
@SerVB Congratulations! Your code have triggered a bug that seems to still be there :)

**Comment by soywiz** [comment]
I have split the initialized properties in several methods, and it seems that it is related somehow to nullability here:

doInitMessagingPolicy

**Comment by soywiz** [comment]
Now it should work (though at runtime in K/N there are still some InvalidMutabilityException).
I'm not rebasing and force pushing to keep the history to open an issue at YouTrack for now at least

**Comment by soywiz** [comment]
Uhm. I guess this time it failed from an OOM error while compiling on windows? I had to do some guesswork adjusting memory assignments in the korge-next repo for the windows target, because GitHub actions assigns less memory to it (or there is more memory consume by the OS)
In my case it usually failed on K/N because had to make some tradeoffs between the memory asigned to the JVM so LLVM compiler/linker didn't fail, but this time it failed on JS 🤔, going to try to set up the CI in my fork

**Comment by SerVB** [comment]
Yeah, would be cool to solve it. But if you don't want to do it, I guess we can just disable problematic targets and merge the PR. Feel free to decide

**Comment by soywiz** [comment]
Ill try to fix the CI issue and the Mutability exception when I have time. If I cannot fix it in a reasonable amount of time, Ill disable the extra targets 👍

**Comment by soywiz** [comment]
Created a new PR to avoid rebasing and force pushing to not mess with the bug report: https://github.com/SerVB/korjector/pull/4
Closing this one

**Pull request closed without merging**
